package exception;

public class FieldCalculator {
    public static void main(String[] args) {
        try {
            int rows = Integer.parseInt(args[0]);
            int columns = Integer.parseInt(args[1]);
            int[][] field = new int[rows][columns];
            int argIndex = 2; 
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < columns; j++) {
                    field[i][j] = Integer.parseInt(args[argIndex]);
                    argIndex++;
                }
            }
            int sum = 0;
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < columns; j++) {
                    sum += field[i][j];
                }
            }
            double average = (double) sum / (rows * columns);
            
            System.out.println("Number of rows: " + rows);
            System.out.println("Number of columns: " + columns);

            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < columns; j++) {
                    System.out.println("el. [" + i + "][" + j + "]: " + field[i][j]);
                }
            }
            
            System.out.println("The sum = " + sum);
            System.out.println("The average = " + average);
        } catch (NumberFormatException | ArrayIndexOutOfBoundsException e) {
            System.out.println("An exception has occurred");
        }
    }
}
